// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoAHjd2z26KGUk3QuMDjSA5bsShkcaj44',
    appId: '1:234797928266:web:5497529cef94c7f87a3bb3',
    messagingSenderId: '234797928266',
    projectId: 'freetalk-52871',
    authDomain: 'freetalk-52871.firebaseapp.com',
    storageBucket: 'freetalk-52871.firebasestorage.app',
    measurementId: 'G-L5R10S59VE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8nN_Zv6Lh0a1d9Mcc4iLmFfm25JY9_gU',
    appId: '1:234797928266:android:a796965366c1c1577a3bb3',
    messagingSenderId: '234797928266',
    projectId: 'freetalk-52871',
    storageBucket: 'freetalk-52871.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC4nubX3jyCX-3C1wlpbTMgyJqABcEVKw',
    appId: '1:234797928266:ios:2536907659539bfb7a3bb3',
    messagingSenderId: '234797928266',
    projectId: 'freetalk-52871',
    storageBucket: 'freetalk-52871.firebasestorage.app',
    iosBundleId: 'com.example.freeTalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC4nubX3jyCX-3C1wlpbTMgyJqABcEVKw',
    appId: '1:234797928266:ios:2536907659539bfb7a3bb3',
    messagingSenderId: '234797928266',
    projectId: 'freetalk-52871',
    storageBucket: 'freetalk-52871.firebasestorage.app',
    iosBundleId: 'com.example.freeTalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoAHjd2z26KGUk3QuMDjSA5bsShkcaj44',
    appId: '1:234797928266:web:e4cce85fbda655247a3bb3',
    messagingSenderId: '234797928266',
    projectId: 'freetalk-52871',
    authDomain: 'freetalk-52871.firebaseapp.com',
    storageBucket: 'freetalk-52871.firebasestorage.app',
    measurementId: 'G-BFL5RRSR7J',
  );
}
